---
layout: post
title: Django SVN Update Goes Splat
date: '2007-05-09T20:30:00.002+10:00'
author: Kelvin Nicholson
tags:
- django
- articles
- doh
modified_time: '2013-01-09T21:33:58.530+11:00'
blogger_id: tag:blogger.com,1999:blog-3439832858234004835.post-3652210710217148262
blogger_orig_url: https://www.kelvinism.com/2007/05/django-svn-update-goes-splat_5490.html
---

I'm writing this just in case somebody runs into this same issue.  I'm about to go live with a website and figured it would be best to have the latest SVN snapshot checked out from Django.  I updated, and noticed that my voting module didn't quite work as expected.  I was getting the following error:<br />
<pre class="brush: python; light: true ">
'module' object has no attribute 'GenericForeignKey'</pre>
<br />
<br />
I jumped into Trac and noticed that <i>just yesterday</i> some things were rearranged.  In short, if you are using generic relations, you'll need to change two parts of your code.  First, the generic relations field must be imported out of conttenttype.<br />
<pre class="brush: python; light: true ">
from django.contrib.contenttypes import generic</pre>
<br />
<br />
And second, you'll need to change the 'location prefix' (for lack of a better description:<br />
<b>From:</b><br />
<pre class="brush: python; light: true ">
generic_field = models.GenericRelation(SomeOtherModel)</pre>
<br />
<br />
<b>To:</b><br />
<pre class="brush: python; light: true ">
generic_field = generic.GenericRelation(SomeOtherModel)</pre>
<br />
<br />
All should be find from there on out.  For more information, take a look at <a href="http://code.djangoproject.com/wiki/BackwardsIncompatibleChanges"> the reference wiki article</a>.